[package]
name = "evina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.23", features = ["derive"] }

chrono = "0.4.26"
fake = { version = "2.8.0", features = ["derive"] }
reqwest = { version = "0.11.19", features = ["json"] }
tokio = { version = "1.32.0", features = ["full"] }
regex = "1.9.3"
boa_engine = "0.16"
md-5 = "0.10.5"
hex = "0.4.3"
serde_json = "1.0.105"
shell-words = "1.1.0"
cookie = { path = "../cookie" }

[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
