name: schedule evina
on: 
  push: 
    branches:
      - master
  schedule: 
    - cron: '*/8 * * * *'

env: 
  TZ: Asia/Shanghai

jobs:
  create_option:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.set-date.outputs.date }}
    steps: 
      - id: set-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: cache option
        id: cache-option
        uses: actions/cache@v4
        with: 
          path: |
            option
          key: ${{ runner.os }}-option-${{ steps.set-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-option-

      - name: download evina
        if: steps.cache-option.outputs.cache-hit != 'true'
        run: |
          mkdir -p option
          wget $(curl https://api.github.com/repos/SuperTreasure/evina/releases/latest | jq -r .assets[3].browser_download_url)
          tar -xvf evina*.tar.xz -C option
          wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n6.1-latest-linux64-gpl-6.1.tar.xz
          # wget $(curl https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/latest | jq -r .assets[36].browser_download_url)
          tar -xvf ffmpeg*.tar.xz -C option
          wget $(curl https://api.github.com/repos/tickstep/aliyunpan/releases/latest | jq -r .assets[10].browser_download_url)
          unzip -o aliyunpan*.zip -d option
          cd ./option/aliyunpan*amd64
          curl ${{ secrets.ALI_TOKEN_URL }} > ./option/aliyunpan*amd64/aliyunpan_config.json && aliyunpan pwd
          # ./option/aliyunpan*amd64/aliyunpan login -RefreshToken=${{ secrets.ALI_TOKEN }}

  douyu:
    needs: create_option
    strategy:
      matrix:
        roomid:
          - 88080

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cache option
        uses: actions/cache@v4
        with:
          path: |
            option
          key: ${{ runner.os }}-option-${{ needs.create_option.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-option-

      - name: create environment 
        run: |
          sudo ln -s $PWD/option/ffmpeg*/bin/ffmpeg /bin/ffmpeg
          sudo ln -s $PWD/option/ffmpeg*/bin/ffprobe /bin/ffprobe
          sudo ln -s $PWD/option/aliyunpan*amd64/aliyunpan /bin/aliyunpan
          sudo ln -s $PWD/option/evina /bin/evina
          
      - name: check ${{ matrix.roomid }}
        id: check_workflow
        uses: ./.github/check
        with: 
          function: check_workflow
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: "schedule evina"
          name_job: "douyu (${{ matrix.roomid }})"
          name_step: "evina ${{ matrix.roomid }}"
          run_number: ${{ github.run_number }}
          num_step: 6

      - name: evina ${{ matrix.roomid }}
        if: steps.check_workflow.outputs.in_progress == 'false'
        run: |
          timeout -k 5 19800 evina -l douyu -i ${{ matrix.roomid }} --bit-rate 40 -m --retry 8 --download-dir 录播 > check.conf

      - name: check evina ${{ matrix.roomid }}
        if: steps.check_workflow.outputs.in_progress == 'false'
        id: check_evina
        run: |
          echo "status=$(cat check.conf | grep -q '未开播' && echo 'true' || echo 'false')"  >> $GITHUB_OUTPUT

      - name: aliyun upload
        if: steps.check_workflow.outputs.in_progress == 'false' && steps.check_evina.outputs.status == 'false'
        uses: ./.github/check
        with: 
          function: ali_upload

  douyin:
    needs: create_option
    strategy:
      matrix:
        roomid:
          - https://live.douyin.com/87356165856
          - https://live.douyin.com/9335670984
          - https://live.douyin.com/194186966318
          - https://live.douyin.com/347239795739
          - https://live.douyin.com/799800642566
          - https://live.douyin.com/653419892304
          - https://live.douyin.com/828466576699
          - https://live.douyin.com/236022333483

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cache option
        uses: actions/cache@v4
        with:
          path: |
            option
          key: ${{ runner.os }}-option-${{ needs.create_option.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-option-

      - name: create environment 
        run: |
          sudo ln -s $PWD/option/ffmpeg*/bin/ffmpeg /bin/ffmpeg
          sudo ln -s $PWD/option/aliyunpan*amd64/aliyunpan /bin/aliyunpan
          sudo ln -s $PWD/option/evina /bin/evina
          
      - name: check workflow ${{ matrix.roomid }}
        id: check_workflow
        uses: ./.github/check
        with: 
          function: check_workflow
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: "schedule evina"
          name_job: "douyin (${{ matrix.roomid }})"
          name_step: "evina ${{ matrix.roomid }}"
          run_number: ${{ github.run_number }}
          num_step: 6

      - name: evina ${{ matrix.roomid }}
        if: steps.check_workflow.outputs.in_progress == 'false'
        run: |
          timeout -k 5 19800 evina -l douyin -i ${{ matrix.roomid }} -m --retry 8 --download-dir 录播 > check.conf

      - name: check evina ${{ matrix.roomid }}
        if: steps.check_workflow.outputs.in_progress == 'false'
        id: check_evina
        run: |
          echo "status=$(cat check.conf | grep -q '未开播' && echo 'true' || echo 'false')"  >> $GITHUB_OUTPUT

      - name: aliyun upload
        if: steps.check_workflow.outputs.in_progress == 'false' && steps.check_evina.outputs.status == 'false'
        uses: ./.github/check
        with: 
          function: ali_upload
