name: schedule evina
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/8 * * * *'

env:
  TZ: Asia/Shanghai

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      douyu: ${{ steps.set-config.outputs.douyu }}
      douyin: ${{ steps.set-config.outputs.douyin }}
    steps:
      - name: set date
        id: set-date
        run: |
          data=$(curl -fsSL ${{secrets.CONFIG_URL}})
          douyu=$(echo $data | jq -c '.douyu')
          douyin=$(echo $data | jq -c '.douyin')
          echo "douyu=$douyu" >> $GITHUB_OUTPUT
          echo "douyin=$douyin" >> $GITHUB_OUTPUT

  douyu:
    needs: config
    strategy:
      matrix:
        roomid: ${{ fromJSON(needs.config.outputs.douyu) }}

    runs-on: ubuntu-latest
    steps:
      - id: set-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: cache option
        uses: actions/cache@v4
        with:
          path: |
            option
          key: ${{ runner.os }}-option-${{ steps.set-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-option-

      - name: create environment
        run: |
          sudo ln -s $PWD/option/ffmpeg*/bin/ffmpeg /bin/ffmpeg
          sudo ln -s $PWD/option/ffmpeg*/bin/ffprobe /bin/ffprobe
          sudo ln -s $PWD/option/aliyunpan*amd64/aliyunpan /bin/aliyunpan
          sudo ln -s $PWD/option/evina /bin/evina

      - name: check ${{ matrix.roomid }}
        id: check_workflow
        uses: ./.github/check
        with:
          function: check_workflow
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: 'schedule evina'
          name_job: 'douyu (${{ matrix.roomid }})'
          name_step: 'evina ${{ matrix.roomid }}'
          run_number: ${{ github.run_number }}
          num_step: 6

      - name: evina ${{ matrix.roomid }}
        if: steps.check_workflow.outputs.in_progress == 'false'
        run: |
          timeout -k 5 19800 evina -l douyu -i ${{ matrix.roomid }} --bit-rate 40 -m --retry 8 --download-dir 录播 > check.conf

      - name: check evina ${{ matrix.roomid }}
        if: steps.check_workflow.outputs.in_progress == 'false'
        id: check_evina
        run: |
          echo "status=$(cat check.conf | grep -q '未开播' && echo 'true' || echo 'false')"  >> $GITHUB_OUTPUT

      - name: aliyun upload
        if: steps.check_workflow.outputs.in_progress == 'false' && steps.check_evina.outputs.status == 'false'
        uses: ./.github/check
        with:
          function: ali_upload

  douyin:
    needs: config
    strategy:
      matrix:
        roomid: ${{ fromJSON(needs.config.outputs.douyin) }}

    runs-on: ubuntu-latest
    steps:
      - id: set-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: cache option
        uses: actions/cache@v4
        with:
          path: |
            option
          key: ${{ runner.os }}-option-${{ steps.set-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-option-

      - name: create environment
        run: |
          sudo ln -s $PWD/option/ffmpeg*/bin/ffmpeg /bin/ffmpeg
          sudo ln -s $PWD/option/aliyunpan*amd64/aliyunpan /bin/aliyunpan
          sudo ln -s $PWD/option/evina /bin/evina

      - name: check workflow ${{ matrix.roomid }}
        id: check_workflow
        uses: ./.github/check
        with:
          function: check_workflow
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: 'schedule evina'
          name_job: 'douyin (${{ matrix.roomid }})'
          name_step: 'evina ${{ matrix.roomid }}'
          run_number: ${{ github.run_number }}
          num_step: 6

      - name: evina ${{ matrix.roomid }}
        if: steps.check_workflow.outputs.in_progress == 'false'
        run: |
          timeout -k 5 19800 evina -l douyin -i ${{ matrix.roomid }} -m --retry 8 --download-dir 录播 > check.conf

      - name: check evina ${{ matrix.roomid }}
        if: steps.check_workflow.outputs.in_progress == 'false'
        id: check_evina
        run: |
          echo "status=$(cat check.conf | grep -q '未开播' && echo 'true' || echo 'false')"  >> $GITHUB_OUTPUT

      - name: aliyun upload
        if: steps.check_workflow.outputs.in_progress == 'false' && steps.check_evina.outputs.status == 'false'
        uses: ./.github/check
        with:
          function: ali_upload

  delete:
    needs: [douyu, douyin]
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 30
